// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ4oyH59S0xtaEYKcIAMjebZGbOzzeln4',
    appId: '1:463233391224:web:08a59d231317c3fd4beb8d',
    messagingSenderId: '463233391224',
    projectId: 'ab-license',
    authDomain: 'ab-license.firebaseapp.com',
    storageBucket: 'ab-license.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTVWdJdTr80VMw3R1lPo_F5yG5-6WibY',
    appId: '1:463233391224:android:2f2d296dac2ded8e4beb8d',
    messagingSenderId: '463233391224',
    projectId: 'ab-license',
    storageBucket: 'ab-license.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoYCpmfnHvig0eGhrI2l1kv7t2i3WZgAk',
    appId: '1:463233391224:ios:0a0fde7d82c644024beb8d',
    messagingSenderId: '463233391224',
    projectId: 'ab-license',
    storageBucket: 'ab-license.appspot.com',
    iosClientId: '463233391224-vkp8uqpatob0jds5v5sa2spk2c8jsodr.apps.googleusercontent.com',
    iosBundleId: 'com.example.testNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoYCpmfnHvig0eGhrI2l1kv7t2i3WZgAk',
    appId: '1:463233391224:ios:0a0fde7d82c644024beb8d',
    messagingSenderId: '463233391224',
    projectId: 'ab-license',
    storageBucket: 'ab-license.appspot.com',
    iosClientId: '463233391224-vkp8uqpatob0jds5v5sa2spk2c8jsodr.apps.googleusercontent.com',
    iosBundleId: 'com.example.testNew',
  );
}
